# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/inputdlg.ui'
#
# Created: Tue Jul 22 18:15:20 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_inputDialog(object):
    def setupUi(self, inputDialog):
        inputDialog.setObjectName(_fromUtf8("inputDialog"))
        inputDialog.resize(396, 448)
        self.verticalLayout_2 = QtGui.QVBoxLayout(inputDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.dateLabel = QtGui.QLabel(inputDialog)
        self.dateLabel.setObjectName(_fromUtf8("dateLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.dateLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.expensesDateEdit = QtGui.QDateEdit(inputDialog)
        self.expensesDateEdit.setCalendarPopup(True)
        self.expensesDateEdit.setObjectName(_fromUtf8("expensesDateEdit"))
        self.horizontalLayout_5.addWidget(self.expensesDateEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.amountLabel = QtGui.QLabel(inputDialog)
        self.amountLabel.setObjectName(_fromUtf8("amountLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.amountLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.amountDoubleSpinBox = QtGui.QDoubleSpinBox(inputDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.amountDoubleSpinBox.setSizePolicy(sizePolicy)
        self.amountDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amountDoubleSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.amountDoubleSpinBox.setAccelerated(True)
        self.amountDoubleSpinBox.setMaximum(1000000.0)
        self.amountDoubleSpinBox.setObjectName(_fromUtf8("amountDoubleSpinBox"))
        self.horizontalLayout_3.addWidget(self.amountDoubleSpinBox)
        self.RUBRadioButton = QtGui.QRadioButton(inputDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RUBRadioButton.sizePolicy().hasHeightForWidth())
        self.RUBRadioButton.setSizePolicy(sizePolicy)
        self.RUBRadioButton.setChecked(True)
        self.RUBRadioButton.setObjectName(_fromUtf8("RUBRadioButton"))
        self.horizontalLayout_3.addWidget(self.RUBRadioButton)
        self.USDRadioButton = QtGui.QRadioButton(inputDialog)
        self.USDRadioButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.USDRadioButton.sizePolicy().hasHeightForWidth())
        self.USDRadioButton.setSizePolicy(sizePolicy)
        self.USDRadioButton.setObjectName(_fromUtf8("USDRadioButton"))
        self.horizontalLayout_3.addWidget(self.USDRadioButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.nameLabel = QtGui.QLabel(inputDialog)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtGui.QLineEdit(inputDialog)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.splitter = QtGui.QSplitter(inputDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tagsGroupBox = QtGui.QGroupBox(self.splitter)
        self.tagsGroupBox.setFlat(True)
        self.tagsGroupBox.setObjectName(_fromUtf8("tagsGroupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tagsGroupBox)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tagsListView = QtGui.QListView(self.tagsGroupBox)
        self.tagsListView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tagsListView.setSelectionRectVisible(True)
        self.tagsListView.setObjectName(_fromUtf8("tagsListView"))
        self.horizontalLayout_4.addWidget(self.tagsListView)
        self.line = QtGui.QFrame(self.tagsGroupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.newTagButton = QtGui.QPushButton(self.tagsGroupBox)
        self.newTagButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newTagButton.sizePolicy().hasHeightForWidth())
        self.newTagButton.setSizePolicy(sizePolicy)
        self.newTagButton.setCheckable(False)
        self.newTagButton.setChecked(False)
        self.newTagButton.setAutoRepeat(False)
        self.newTagButton.setFlat(False)
        self.newTagButton.setObjectName(_fromUtf8("newTagButton"))
        self.verticalLayout.addWidget(self.newTagButton)
        self.deleteTagButton = QtGui.QPushButton(self.tagsGroupBox)
        self.deleteTagButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteTagButton.sizePolicy().hasHeightForWidth())
        self.deleteTagButton.setSizePolicy(sizePolicy)
        self.deleteTagButton.setCheckable(False)
        self.deleteTagButton.setChecked(False)
        self.deleteTagButton.setAutoRepeat(False)
        self.deleteTagButton.setFlat(False)
        self.deleteTagButton.setObjectName(_fromUtf8("deleteTagButton"))
        self.verticalLayout.addWidget(self.deleteTagButton)
        self.selectAllTagsButton = QtGui.QPushButton(self.tagsGroupBox)
        self.selectAllTagsButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectAllTagsButton.sizePolicy().hasHeightForWidth())
        self.selectAllTagsButton.setSizePolicy(sizePolicy)
        self.selectAllTagsButton.setCheckable(False)
        self.selectAllTagsButton.setChecked(False)
        self.selectAllTagsButton.setAutoRepeat(False)
        self.selectAllTagsButton.setFlat(False)
        self.selectAllTagsButton.setObjectName(_fromUtf8("selectAllTagsButton"))
        self.verticalLayout.addWidget(self.selectAllTagsButton)
        self.deselectAllTagsButton = QtGui.QPushButton(self.tagsGroupBox)
        self.deselectAllTagsButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deselectAllTagsButton.sizePolicy().hasHeightForWidth())
        self.deselectAllTagsButton.setSizePolicy(sizePolicy)
        self.deselectAllTagsButton.setCheckable(False)
        self.deselectAllTagsButton.setChecked(False)
        self.deselectAllTagsButton.setAutoRepeat(False)
        self.deselectAllTagsButton.setFlat(False)
        self.deselectAllTagsButton.setObjectName(_fromUtf8("deselectAllTagsButton"))
        self.verticalLayout.addWidget(self.deselectAllTagsButton)
        spacerItem2 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.commentsGroupBox = QtGui.QGroupBox(self.splitter)
        self.commentsGroupBox.setFlat(True)
        self.commentsGroupBox.setCheckable(False)
        self.commentsGroupBox.setObjectName(_fromUtf8("commentsGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.commentsGroupBox)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(0, 9, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.commentsPlainTextEdit = QtGui.QPlainTextEdit(self.commentsGroupBox)
        self.commentsPlainTextEdit.setPlainText(_fromUtf8(""))
        self.commentsPlainTextEdit.setObjectName(_fromUtf8("commentsPlainTextEdit"))
        self.horizontalLayout_2.addWidget(self.commentsPlainTextEdit)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.commentsButton = QtGui.QPushButton(inputDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentsButton.sizePolicy().hasHeightForWidth())
        self.commentsButton.setSizePolicy(sizePolicy)
        self.commentsButton.setCheckable(True)
        self.commentsButton.setChecked(False)
        self.commentsButton.setObjectName(_fromUtf8("commentsButton"))
        self.horizontalLayout.addWidget(self.commentsButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.discardButton = QtGui.QPushButton(inputDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.discardButton.sizePolicy().hasHeightForWidth())
        self.discardButton.setSizePolicy(sizePolicy)
        self.discardButton.setObjectName(_fromUtf8("discardButton"))
        self.horizontalLayout.addWidget(self.discardButton)
        self.addButton = QtGui.QPushButton(inputDialog)
        self.addButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.horizontalLayout.addWidget(self.addButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.dateLabel.setBuddy(self.expensesDateEdit)
        self.amountLabel.setBuddy(self.amountDoubleSpinBox)
        self.nameLabel.setBuddy(self.nameLineEdit)

        self.retranslateUi(inputDialog)
        QtCore.QMetaObject.connectSlotsByName(inputDialog)
        inputDialog.setTabOrder(self.amountDoubleSpinBox, self.nameLineEdit)
        inputDialog.setTabOrder(self.nameLineEdit, self.commentsPlainTextEdit)

    def retranslateUi(self, inputDialog):
        inputDialog.setWindowTitle(_translate("inputDialog", "Dialog", None))
        self.dateLabel.setText(_translate("inputDialog", "&Date:", None))
        self.expensesDateEdit.setDisplayFormat(_translate("inputDialog", "dd/MM/yyyy", None))
        self.amountLabel.setText(_translate("inputDialog", "Exp. &amount:", None))
        self.amountDoubleSpinBox.setPrefix(_translate("inputDialog", "P ", None))
        self.RUBRadioButton.setText(_translate("inputDialog", "P", None))
        self.USDRadioButton.setText(_translate("inputDialog", "$", None))
        self.nameLabel.setText(_translate("inputDialog", "Exp. &name:", None))
        self.tagsGroupBox.setTitle(_translate("inputDialog", "Tags:", None))
        self.newTagButton.setText(_translate("inputDialog", "New", None))
        self.deleteTagButton.setText(_translate("inputDialog", "Delete", None))
        self.selectAllTagsButton.setText(_translate("inputDialog", "Select All", None))
        self.deselectAllTagsButton.setText(_translate("inputDialog", "Deselect All", None))
        self.commentsGroupBox.setTitle(_translate("inputDialog", "Comments:", None))
        self.commentsButton.setText(_translate("inputDialog", "Comments...", None))
        self.discardButton.setText(_translate("inputDialog", "Discard", None))
        self.addButton.setText(_translate("inputDialog", "Add", None))

